name: MetaCall Distributable Windows Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  checkout_and_build_core:
    runs-on: windows-2019
    steps:
      - name: Checkout MetaCall Core Repository
        uses: actions/checkout@v2
        with:
          repository: metacall/core
          ref: ${{ github.event.ref }}

      - name: Set up Visual Studio Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build MetaCall Core
        shell: powershell
        run: .\build.bat

      - name: Test MetaCall Core
        shell: powershell
        run: .\test.bat

  checkout_and_build_distributable:
    runs-on: windows-2019
    steps:
      - name: Checkout Current Distributable Repository
        uses: actions/checkout@v2

      - name: Build Distributable
        shell: powershell
        run: .\build.bat

      - name: Test Distributable
        shell: powershell
        run: .\test.bat

  release:
    needs: [checkout_and_build_core, checkout_and_build_distributable]
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: metacall-tarball-win-x64.zip
          fail_on_unmatched_files: true
