name: MetaCall Distributable Windows Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        shell: powershell
        run: .\build.bat
      - name: Test
        shell: powershell
        run: .\test.bat
